jobs:
  check_formatting:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        CI: 1
      name: Run format.sh and print changes
      run: './format.sh

        git diff

        '
    - continue-on-error: true
      name: Check for changes
      run: '[ $(git status --porcelain | wc -l) -eq 0 ]'
name: Check formatting
on:
  repository_dispatch:
    types: trigger-ga___check-formatting.yml
