jobs:
  send-release-event:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Send Release Event
      run: "curl -sX POST \"https://api.datadoghq.eu/api/v1/events\" \\\n  -H \"Accept:\
        \ application/json\" \\\n  -H \"Content-Type: application/json\" \\\n  -H\
        \ \"DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}\" \\\n  --data-raw '{\n   \
        \ \"title\": \"Jazzer has been released\",\n    \"text\": \"%%% \\nJazzer\
        \ has been released with version **${{ github.event.release.tag_name }}**\\\
        n %%%\",\n    \"tags\": [\n      \"repo:${{ github.repository }}\",\n    \
        \  \"project:Jazzer\",\n      \"version:${{ github.event.release.tag_name\
        \ }}\"\n    ]\n  }'\n"
name: Datadog Event
on:
  repository_dispatch:
    types: trigger-ga___datadog.yaml
