jobs:
  docker_push:
    environment:
      name: Deploy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Docker login
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USER
        }} --password-stdin
    - continue-on-error: true
      name: Push docker containers
      run: docker/push_all.sh
  generate_docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Build documentation
      run: 'bazel build //deploy:jazzer-docs //deploy:jazzer-api-docs //deploy:jazzer-junit-docs

        cp $(bazel cquery --output=files //deploy:jazzer-docs) ./jazzer-docs.jar

        cp $(bazel cquery --output=files //deploy:jazzer-api-docs) ./jazzer-api-docs.jar

        cp $(bazel cquery --output=files //deploy:jazzer-junit-docs) ./jazzer-junit-docs.jar

        '
    - continue-on-error: true
      name: Upload jars
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: jazzer_docs_jars
        path: 'jazzer-docs.jar

          jazzer-api-docs.jar

          jazzer-junit-docs.jar

          '
  update_docs:
    environment:
      name: Deploy
    needs: generate_docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout docs
      uses: actions/checkout@v3
      with:
        repository: CodeIntelligenceTesting/jazzer-docs
        ssh-key: ${{ secrets.JAZZER_DOCS_SSH_KEY_PRIVATE }}
    - continue-on-error: true
      name: Download jar
      uses: actions/download-artifact@v3
      with:
        name: jazzer_docs_jars
        path: .
    - continue-on-error: true
      name: Setup git
      run: 'git config user.email "info@code-intelligence.com"

        git config user.name "Jazzer release pipeline"

        '
    - continue-on-error: true
      name: Extract API docs jar
      run: 'git rm -rf jazzer-api

        mkdir jazzer-api

        unzip jazzer-api-docs.jar -d jazzer-api

        git add jazzer-api

        # Do not fail if no changes to commit

        # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error

        git diff-index --quiet HEAD || git commit -m "Automated update: jazzer-api
        docs"

        '
    - continue-on-error: true
      name: Extract Jazzer docs jar
      run: 'git rm -rf jazzer

        mkdir jazzer

        unzip jazzer-docs.jar -d jazzer

        git add jazzer

        git diff-index --quiet HEAD || git commit -m "Automated update: jazzer docs"

        '
    - continue-on-error: true
      name: Extract JUnit docs jar
      run: 'git rm -rf jazzer-junit

        mkdir jazzer-junit

        unzip jazzer-junit-docs.jar -d jazzer-junit

        git add jazzer-junit

        git diff-index --quiet HEAD || git commit -m "Automated update: jazzer-junit
        docs"

        '
    - continue-on-error: true
      name: Push changes
      run: 'git push

        '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
