jobs:
  build_and_test:
    name: Build & Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      if: contains(matrix.os, 'mac')
      name: Remove codesign signature on java binary
      run: codesign --remove-signature "$JAVA_HOME"/bin/java
    - continue-on-error: true
      name: Set Build Buddy config
      run: .github/scripts/echoBuildBuddyConfig.sh ${{ secrets.BUILDBUDDY_API_KEY
        }} >> $GITHUB_ENV
      shell: bash
    - continue-on-error: true
      name: Build & Test
      run: bazelisk test ${{env.BUILD_BUDDY_CONFIG}} --java_runtime_version=local_jdk_${{
        matrix.jdk }} ${{ matrix.bazel_args }} ${{ matrix.extra_bazel_args }} --build_tag_filters="-no-${{
        matrix.arch }}-jdk${{ matrix.jdk }},-no-jdk${{ matrix.jdk }}" --test_tag_filters="-no-${{
        matrix.arch }}-jdk${{ matrix.jdk }},-no-jdk${{ matrix.jdk }}" //...
    - continue-on-error: true
      if: always()
      name: Copy Bazel log
      run: cp "$(readlink bazel-out)"/../../../java.log* .
      shell: bash
    - continue-on-error: true
      if: always()
      name: Upload test logs
      uses: actions/upload-artifact@v3
      with:
        name: testlogs-${{ matrix.arch }}-${{ matrix.jdk }}
        path: 'bazel-testlogs*/**/test.log

          java.log*

          '
    strategy:
      matrix:
        include:
        - extra_bazel_args: --jvmopt=-Djava.security.manager=allow
          jdk: 21
        - arch: linux
          bazel_args: //launcher/android:jazzer_android //tests/benchmarks
          os: ubuntu-20.04
        - arch: macos-x86_64
          bazel_args: --xcode_version_config=//.github:host_xcodes //launcher/android:jazzer_android
          os: macos-12
        - arch: windows
          os: windows-2019
        jdk:
        - 8
        - 21
        os:
        - ubuntu-20.04
        - macos-12
        - windows-2019
  test_junit_springboot:
    name: Spring Boot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Run Spring Boot example
      run: 'cd examples/junit-spring-web

        ./build-and-run-tests.sh

        '
      shell: bash
name: CI
on:
  repository_dispatch:
    types: trigger-ga___run-all-tests.yml
